# Generated by Django 2.1.3 on 2018-11-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20181119_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
